/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import App.HintSupport;
import BLL.DonViVanChuyenBLL;
import DTO.DonViVanChuyenDTO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nghia
 */
public class ChildformQLDVVC extends javax.swing.JPanel {
    
    private DonViVanChuyenBLL bll = new DonViVanChuyenBLL();
    DecimalFormat df = new DecimalFormat("#,###");

    /**
     * Creates new form ChildformQLDVVC
     */
    public ChildformQLDVVC() {
        initComponents();
        
        HintSupport.addHint(tf_emaildvvc, "Nhập email...");
        HintSupport.addHint(tf_loaivanchuyen, "Nhập loại vận chuyển...");
        HintSupport.addHint(tf_madvvc, "Nhập mã...");
        HintSupport.addHint(tf_nguoilh, "Nhập tên người liên hệ...");
        HintSupport.addHint(tf_sdtdvvc, "Nhập số điện thoại...");
        HintSupport.addHint(tf_tencongty, "Nhập tên công ty...");
        HintSupport.addHint(tf_tggiaohang, "Nhập thời gian giao hàng trung bình...");
        HintSupport.addHint(tf_timkiem, "Tìm Kiếm");
        HintSupport.addHint(tf_phivanchuyen, "Nhập phí vận chuyển...");
        
        cauHinhBang(); 
        loadTable();
        
    }
    
    private void cauHinhBang() {
        
        String[] columnNames = {
            "Mã DVVC", "Tên Công Ty", "SĐT", "Email", "Người Liên Hệ", "Loại VC", "Thời Gian", "Phí Ship"
        };

        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Trả về false để KHÔNG cho sửa
            }
        };
        
        Tb_Dulieu.setModel(model);
    }
    
    public void loadTable() {
        DefaultTableModel model = (DefaultTableModel) Tb_Dulieu.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        
        ArrayList<DonViVanChuyenDTO> list = bll.layDanhSach();
        
        for (DonViVanChuyenDTO x : list) {
            model.addRow(new Object[]{
                x.getMaDVVC(),
                x.getTenCongTy(),
                x.getSdt(),
                x.getEmail(),
                x.getNguoiLienHe(),
                x.getLoaiVanChuyen(),
                x.getThoiGianGiao(),
                df.format(x.getPhiVanChuyen())
            });
        }
    }
    
    private void lamMoiForm() {
        tf_madvvc.setText("");
        tf_tencongty.setText("");
        tf_sdtdvvc.setText("");
        tf_emaildvvc.setText("");
        tf_nguoilh.setText("");
        tf_loaivanchuyen.setText("");
        tf_tggiaohang.setText("");
        tf_phivanchuyen.setText("");
        // Vì bạn dùng HintSupport, có thể cần focus lại hoặc set lại hint nếu cần
        tf_tencongty.requestFocus(); 
    }
    
    private void xuLyTimKiem() {
        // 1. Lấy từ khóa
        String tuKhoa = tf_timkiem.getText();
        
        // 2. Gọi BLL tìm kiếm
        // (Hàm này đã xử lý trường hợp rỗng hoặc chữ gợi ý bên BLL rồi)
        ArrayList<DonViVanChuyenDTO> ketQua = bll.timKiemDVVC(tuKhoa);
        
        // 3. Đổ dữ liệu mới vào bảng
        DefaultTableModel model = (DefaultTableModel) Tb_Dulieu.getModel();
        model.setRowCount(0); // Xóa sạch dữ liệu cũ
        
        for (DonViVanChuyenDTO x : ketQua) {
            model.addRow(new Object[]{
                x.getMaDVVC(),
                x.getTenCongTy(),
                x.getSdt(),
                x.getEmail(),
                x.getNguoiLienHe(),
                x.getLoaiVanChuyen(),
                x.getThoiGianGiao(),
                x.getPhiVanChuyen()
            });
        }
    }
    
    private java.awt.Component getFrame() {
        return javax.swing.SwingUtilities.getWindowAncestor(this);
    }
    
    private boolean checkInput(javax.swing.JTextField tf, String hint, String fieldName) {
        String text = tf.getText().trim();
        if (text.isEmpty() || text.equals(hint)) {
            javax.swing.JOptionPane.showMessageDialog(getFrame(), "Vui lòng nhập " + fieldName + "!");
            tf.requestFocus(); // Đưa con trỏ chuột về ô bị thiếu
            return true; // Có lỗi
        }
        return false; // Không có lỗi, dữ liệu hợp lệ
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_tencongty = new javax.swing.JTextField();
        tf_sdtdvvc = new javax.swing.JTextField();
        tf_emaildvvc = new javax.swing.JTextField();
        tf_nguoilh = new javax.swing.JTextField();
        lbl_nguoilh = new javax.swing.JLabel();
        lbl_emaildvvc = new javax.swing.JLabel();
        lbl_sdtdvvc = new javax.swing.JLabel();
        lbl_tencongti = new javax.swing.JLabel();
        tf_loaivanchuyen = new javax.swing.JTextField();
        lbl_loaivanchuyen = new javax.swing.JLabel();
        lbl_tggiaohang = new javax.swing.JLabel();
        tf_tggiaohang = new javax.swing.JTextField();
        lbl_madvvc = new javax.swing.JLabel();
        tf_madvvc = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        tf_timkiem = new javax.swing.JTextField();
        lbl_madvvc1 = new javax.swing.JLabel();
        lbl_tggiaohang1 = new javax.swing.JLabel();
        tf_phivanchuyen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Dulieu = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 238, 240));

        tf_tencongty.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_tencongty.setText("jTextField1");
        tf_tencongty.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_sdtdvvc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_sdtdvvc.setText("jTextField1");
        tf_sdtdvvc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_emaildvvc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_emaildvvc.setText("jTextField1");
        tf_emaildvvc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_nguoilh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_nguoilh.setText("jTextField1");
        tf_nguoilh.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_nguoilh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nguoilh.setText("Người Liện Hệ Chính:");
        lbl_nguoilh.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_emaildvvc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_emaildvvc.setText("Email:");
        lbl_emaildvvc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_sdtdvvc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_sdtdvvc.setText("SDT Liên Hệ:");
        lbl_sdtdvvc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_tencongti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tencongti.setText("Công Ty:");
        lbl_tencongti.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_loaivanchuyen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_loaivanchuyen.setText("jTextField1");
        tf_loaivanchuyen.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_loaivanchuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_loaivanchuyen.setText("Loại Vận Chuyển:");
        lbl_loaivanchuyen.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_tggiaohang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tggiaohang.setText("Thời Gian Giao Hàng:");
        lbl_tggiaohang.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_tggiaohang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_tggiaohang.setText("jTextField1");
        tf_tggiaohang.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_madvvc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_madvvc.setText("Mã DVVC:");
        lbl_madvvc.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_madvvc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_madvvc.setText("jTextField1");
        tf_madvvc.setPreferredSize(new java.awt.Dimension(86, 16));

        btn_them.setBackground(new java.awt.Color(50, 50, 50));
        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.setBorderPainted(false);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        tf_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_timkiem.setText("jTextField1");
        tf_timkiem.setPreferredSize(new java.awt.Dimension(86, 16));
        tf_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_timkiemKeyReleased(evt);
            }
        });

        lbl_madvvc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_madvvc1.setText("Tìm Kiếm:");
        lbl_madvvc1.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_tggiaohang1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tggiaohang1.setText("Phí Vận Chuyển:");
        lbl_tggiaohang1.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_phivanchuyen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_phivanchuyen.setText("jTextField1");
        tf_phivanchuyen.setPreferredSize(new java.awt.Dimension(86, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tencongti, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sdtdvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_emaildvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_madvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_tencongty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_sdtdvvc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_emaildvvc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_madvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_loaivanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tggiaohang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tggiaohang1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nguoilh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_loaivanchuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_tggiaohang, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(tf_phivanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(lbl_madvvc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tencongty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tencongti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sdtdvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sdtdvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_emaildvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_emaildvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_madvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_madvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tggiaohang1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_phivanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_loaivanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_loaivanchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tggiaohang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tggiaohang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_madvvc1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 310));

        Tb_Dulieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_Dulieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_DulieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_Dulieu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1250, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (checkInput(tf_madvvc, "Nhập mã...", "Mã ĐVVC")) return;
        if (checkInput(tf_tencongty, "Nhập tên công ty...", "Tên Công Ty")) return;
        if (checkInput(tf_sdtdvvc, "Nhập số điện thoại...", "Số Điện Thoại")) return;
        if (checkInput(tf_emaildvvc, "Nhập email...", "Email")) return;
        if (checkInput(tf_nguoilh, "Nhập tên người liên hệ...", "Người Liên Hệ Chính")) return;
        if (checkInput(tf_loaivanchuyen, "Nhập loại vận chuyển...", "Loại Vận Chuyển")) return;
        if (checkInput(tf_tggiaohang, "Nhập thời gian giao hàng trung bình...", "Thời Gian Giao Hàng")) return;
        if (checkInput(tf_phivanchuyen, "Nhập phí vận chuyển...", "Phí Vận Chuyển")) return;

        DonViVanChuyenDTO dv = new DonViVanChuyenDTO();
        dv.setMaDVVC(tf_madvvc.getText());
        dv.setTenCongTy(tf_tencongty.getText());
        dv.setSdt(tf_sdtdvvc.getText());
        dv.setEmail(tf_emaildvvc.getText());
        dv.setNguoiLienHe(tf_nguoilh.getText());
        dv.setLoaiVanChuyen(tf_loaivanchuyen.getText());
        dv.setThoiGianGiao(tf_tggiaohang.getText());
        try {
            double phi = Double.parseDouble(tf_phivanchuyen.getText());
            if (phi < 0) {
                javax.swing.JOptionPane.showMessageDialog(getFrame(), "Phí vận chuyển không được âm!");
                return;
            }
            dv.setPhiVanChuyen(phi);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(getFrame(), "Phí vận chuyển phải là số!");
            return;
        }
        
        String ketQua = bll.themDVVC(dv);

        javax.swing.JOptionPane.showMessageDialog(getFrame(), ketQua);

        if (ketQua.contains("thành công")) {
            loadTable();
            lamMoiForm();
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void Tb_DulieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_DulieuMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = Tb_Dulieu.getSelectedRow();
            if (row >= 0) {
                
                String ma = Tb_Dulieu.getValueAt(row, 0).toString();
                String ten = Tb_Dulieu.getValueAt(row, 1).toString();
                String sdt = Tb_Dulieu.getValueAt(row, 2).toString();
                String email = Tb_Dulieu.getValueAt(row, 3).toString();
                String nguoilh = Tb_Dulieu.getValueAt(row, 4).toString();
                String loai = Tb_Dulieu.getValueAt(row, 5).toString();
                String tg = Tb_Dulieu.getValueAt(row, 6).toString();
                String phiShip = Tb_Dulieu.getValueAt(row, 7).toString();

                java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
                FormSuaDVVC suadvvc = new FormSuaDVVC(parent, true);
                
                suadvvc.setDuLieu(ma, ten, sdt, email, nguoilh, loai, tg, phiShip);
                
                suadvvc.setTitle("Cập Nhật Đơn Vị Vận Chuyển");
                suadvvc.setVisible(true);
                loadTable(); 
            }
        }
    }//GEN-LAST:event_Tb_DulieuMouseClicked

    private void tf_timkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_timkiemKeyReleased
        // TODO add your handling code here:
        xuLyTimKiem();
    }//GEN-LAST:event_tf_timkiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_Dulieu;
    private javax.swing.JButton btn_them;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_emaildvvc;
    private javax.swing.JLabel lbl_loaivanchuyen;
    private javax.swing.JLabel lbl_madvvc;
    private javax.swing.JLabel lbl_madvvc1;
    private javax.swing.JLabel lbl_nguoilh;
    private javax.swing.JLabel lbl_sdtdvvc;
    private javax.swing.JLabel lbl_tencongti;
    private javax.swing.JLabel lbl_tggiaohang;
    private javax.swing.JLabel lbl_tggiaohang1;
    private javax.swing.JTextField tf_emaildvvc;
    private javax.swing.JTextField tf_loaivanchuyen;
    private javax.swing.JTextField tf_madvvc;
    private javax.swing.JTextField tf_nguoilh;
    private javax.swing.JTextField tf_phivanchuyen;
    private javax.swing.JTextField tf_sdtdvvc;
    private javax.swing.JTextField tf_tencongty;
    private javax.swing.JTextField tf_tggiaohang;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
}
