/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import App.HintSupport;
import BLL.NhaCungCapBLL;
import DTO.NhaCungCapDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nghia
 */
public class ChildformQLNCC extends javax.swing.JPanel {
    
    private NhaCungCapBLL bll = new NhaCungCapBLL();

    /**
     * Creates new form ChildformQLNCC
     */
    public ChildformQLNCC() {
        initComponents();
        
        // TextHint
        HintSupport.addHint(tf_diachincc, "Nhập địa chỉ...");
        HintSupport.addHint(tf_mancc, "Nhập mã nhà cung cấp...");
        HintSupport.addHint(tf_emailncc,"Nhập email...");
        HintSupport.addHint(tf_nguoilh, "Nhập tên người liên hệ chính...");
        HintSupport.addHint(tf_sdtncc, "Nhập SDT...");
        HintSupport.addHint(tf_timkiem, "Tìm Kiếm");
        HintSupport.addHint(tf_tencongtyncc, "Nhập tên công ty...");
        
        cauHinhBang();
        loadTable();
    }
    
    private void cauHinhBang() {
        String[] headers = {"Mã NCC", "Tên Công Ty", "Địa Chỉ", "SĐT", "Email", "Người Liên Hệ"};
        DefaultTableModel model = new DefaultTableModel(headers, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Quan trọng: Không cho sửa trên bảng
            }
        };
        tb_dulieu.setModel(model);
    }
    
    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tb_dulieu.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        
        ArrayList<NhaCungCapDTO> list = bll.layDanhSach();
        for (NhaCungCapDTO x : list) {
            model.addRow(new Object[]{
                x.getMaNCC(), x.getTenCongTy(), x.getDiaChi(), 
                x.getSdt(), x.getEmail(), x.getNguoiLienHe()
            });
        }
    }
    
    private void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tb_dulieu.getModel();
        model.setRowCount(0);
        
        String tuKhoa = tf_timkiem.getText();
        ArrayList<NhaCungCapDTO> list = bll.timKiemNCC(tuKhoa);
        
        for (NhaCungCapDTO x : list) {
            model.addRow(new Object[]{
                x.getMaNCC(), x.getTenCongTy(), x.getDiaChi(), 
                x.getSdt(), x.getEmail(), x.getNguoiLienHe()
            });
        }
    }
    
    private boolean checkInput(javax.swing.JTextField tf, String hint, String name) {
        if (tf.getText().trim().isEmpty() || tf.getText().equals(hint)) {
            JOptionPane.showMessageDialog(getFrame(), "Vui lòng nhập " + name + "!");
            tf.requestFocus();
            return true; // Có lỗi
        }
        return false; // Không lỗi
    }

    private java.awt.Component getFrame() {
        return javax.swing.SwingUtilities.getWindowAncestor(this);
    }
    
    private void lamMoiForm() {
        tf_mancc.setText(""); tf_tencongtyncc.setText(""); tf_diachincc.setText("");
        tf_sdtncc.setText(""); tf_emailncc.setText(""); tf_nguoilh.setText("");
        tf_mancc.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_thongtin = new javax.swing.JPanel();
        lbl_diachincc = new javax.swing.JLabel();
        lbl_sdtncc = new javax.swing.JLabel();
        lbl_nguoilh = new javax.swing.JLabel();
        lbl_emailncc = new javax.swing.JLabel();
        tf_diachincc = new javax.swing.JTextField();
        tf_sdtncc = new javax.swing.JTextField();
        tf_emailncc = new javax.swing.JTextField();
        tf_nguoilh = new javax.swing.JTextField();
        lbl_mancc = new javax.swing.JLabel();
        tf_mancc = new javax.swing.JTextField();
        tf_timkiem = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        tf_tencongtyncc = new javax.swing.JTextField();
        lbl_tencongtyncc = new javax.swing.JLabel();
        lbl_timkiem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dulieu = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_thongtin.setBackground(new java.awt.Color(235, 238, 240));

        lbl_diachincc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_diachincc.setText("Địa Chỉ:");
        lbl_diachincc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_sdtncc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_sdtncc.setText("SDT Liên Hệ:");
        lbl_sdtncc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_nguoilh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nguoilh.setText("Người Liện Hệ Chính:");
        lbl_nguoilh.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_emailncc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_emailncc.setText("Email:");
        lbl_emailncc.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_diachincc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_diachincc.setText("jTextField1");
        tf_diachincc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_sdtncc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_sdtncc.setText("jTextField1");
        tf_sdtncc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_emailncc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_emailncc.setText("jTextField1");
        tf_emailncc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_nguoilh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_nguoilh.setText("jTextField1");
        tf_nguoilh.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_mancc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_mancc.setText("Mã Nhà Cung Cấp:");
        lbl_mancc.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_mancc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_mancc.setText("jTextField1");
        tf_mancc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_timkiem.setText("jTextField1");
        tf_timkiem.setPreferredSize(new java.awt.Dimension(86, 16));
        tf_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_timkiemKeyReleased(evt);
            }
        });

        btn_them.setBackground(new java.awt.Color(50, 50, 50));
        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.setBorderPainted(false);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        tf_tencongtyncc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_tencongtyncc.setText("jTextField1");
        tf_tencongtyncc.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_tencongtyncc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tencongtyncc.setText("Tên Công Ty:");
        lbl_tencongtyncc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_timkiem.setText("Tìm Kiếm:");
        lbl_timkiem.setPreferredSize(new java.awt.Dimension(85, 16));

        javax.swing.GroupLayout Pnl_thongtinLayout = new javax.swing.GroupLayout(Pnl_thongtin);
        Pnl_thongtin.setLayout(Pnl_thongtinLayout);
        Pnl_thongtinLayout.setHorizontalGroup(
            Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_thongtinLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_sdtncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_tencongtyncc, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(tf_diachincc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_sdtncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_emailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_emailncc, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(tf_nguoilh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_mancc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(lbl_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pnl_thongtinLayout.setVerticalGroup(
            Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_emailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_emailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        add(Pnl_thongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 310));

        tb_dulieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_dulieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dulieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dulieu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1250, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void tf_timkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_timkiemKeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_tf_timkiemKeyReleased

    private void tb_dulieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dulieuMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { // Kiểm tra click đúp
            int row = tb_dulieu.getSelectedRow();
            if (row >= 0) {

                String ma = tb_dulieu.getValueAt(row, 0).toString();
                String ten = tb_dulieu.getValueAt(row, 1).toString();
                String diachi = tb_dulieu.getValueAt(row, 2).toString();
                String sdt = tb_dulieu.getValueAt(row, 3).toString();
                String email = tb_dulieu.getValueAt(row, 4).toString();
                String nguoilh = tb_dulieu.getValueAt(row, 5).toString();

                java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
                FormSuaNCC formSua = new FormSuaNCC(parent, true);
                
                formSua.setDuLieu(ma, ten, diachi, sdt, email, nguoilh); // Truyền dữ liệu
                formSua.setTitle("Cập Nhật Nhà Cung Cấp");
                formSua.setVisible(true); // Code sẽ dừng tại đây chờ Form sửa đóng lại
                
                loadTable();
            }
        }
    }//GEN-LAST:event_tb_dulieuMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:

        if (checkInput(tf_mancc, "Nhập mã nhà cung cấp...", "Mã NCC")) return;
        if (checkInput(tf_tencongtyncc, "Nhập tên công ty...", "Tên Công Ty")) return;
        if (checkInput(tf_diachincc, "Nhập địa chỉ...", "Địa Chỉ")) return;
        if (checkInput(tf_sdtncc, "Nhập SDT...", "Số Điện Thoại")) return;
        if (checkInput(tf_emailncc, "Nhập email...", "Email")) return;
        if (checkInput(tf_nguoilh, "Nhập tên người liên hệ chính...", "Người Liên Hệ")) return;

        DTO.NhaCungCapDTO ncc = new DTO.NhaCungCapDTO();
        
        ncc.setMaNCC(tf_mancc.getText().trim());
        ncc.setTenCongTy(tf_tencongtyncc.getText().trim());
        ncc.setDiaChi(tf_diachincc.getText().trim());
        ncc.setSdt(tf_sdtncc.getText().trim());
        ncc.setEmail(tf_emailncc.getText().trim());
        ncc.setNguoiLienHe(tf_nguoilh.getText().trim());

        String ketQua = bll.themNCC(ncc);
        
        javax.swing.JOptionPane.showMessageDialog(getFrame(), ketQua);

        if (ketQua.contains("thành công")) {
            loadTable();   // Load lại bảng để thấy dòng mới
            lamMoiForm();  // Xóa trắng các ô nhập liệu
        }
    }//GEN-LAST:event_btn_themActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_thongtin;
    private javax.swing.JButton btn_them;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_diachincc;
    private javax.swing.JLabel lbl_emailncc;
    private javax.swing.JLabel lbl_mancc;
    private javax.swing.JLabel lbl_nguoilh;
    private javax.swing.JLabel lbl_sdtncc;
    private javax.swing.JLabel lbl_tencongtyncc;
    private javax.swing.JLabel lbl_timkiem;
    private javax.swing.JTable tb_dulieu;
    private javax.swing.JTextField tf_diachincc;
    private javax.swing.JTextField tf_emailncc;
    private javax.swing.JTextField tf_mancc;
    private javax.swing.JTextField tf_nguoilh;
    private javax.swing.JTextField tf_sdtncc;
    private javax.swing.JTextField tf_tencongtyncc;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
}
