/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Nghia
 */
public class ChildformTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form ChildformTaiKhoan
     */
    public ChildformTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_avatar = new javax.swing.JLabel();
        btn_capnhatanh = new javax.swing.JButton();
        lbl_header_tennguoidung = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_title_tennguoidung = new javax.swing.JLabel();
        lbl_title_taikhoan = new javax.swing.JLabel();
        lbl_title_matkhau = new javax.swing.JLabel();
        lbl_title_diachi = new javax.swing.JLabel();
        lbl_title_email = new javax.swing.JLabel();
        btn_doimatkhau = new javax.swing.JButton();
        lbl_title_sdt = new javax.swing.JLabel();
        lbl_tennguoidung = new javax.swing.JLabel();
        lbl_taikhoan = new javax.swing.JLabel();
        lbl_matkhau = new javax.swing.JLabel();
        lbl_diachi = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_sdt = new javax.swing.JLabel();
        btn_dangxuat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1250, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));

        lbl_avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gumayusianhdaihien.jpg"))); // NOI18N

        btn_capnhatanh.setBackground(new java.awt.Color(50, 50, 50));
        btn_capnhatanh.setForeground(new java.awt.Color(255, 255, 255));
        btn_capnhatanh.setText("Cập Nhật Ảnh Đại Diện");
        btn_capnhatanh.setBorderPainted(false);

        lbl_header_tennguoidung.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_header_tennguoidung.setForeground(new java.awt.Color(255, 255, 255));
        lbl_header_tennguoidung.setText("Tên Người Dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lbl_avatar)
                        .addGap(33, 33, 33)
                        .addComponent(lbl_header_tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_capnhatanh, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(763, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_avatar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_header_tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_capnhatanh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("THÔNG TIN NGƯỜI DÙNG:");

        lbl_title_tennguoidung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_tennguoidung.setText("Tên Người Dùng:");

        lbl_title_taikhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_taikhoan.setText("Tài Khoản:");

        lbl_title_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_matkhau.setText("Mật Khẩu:");
        lbl_title_matkhau.setToolTipText("");

        lbl_title_diachi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_diachi.setText("Mã Nhân Viên:");
        lbl_title_diachi.setToolTipText("");

        lbl_title_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_email.setText("Email:");

        btn_doimatkhau.setBackground(new java.awt.Color(50, 50, 50));
        btn_doimatkhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_doimatkhau.setText("Đổi Mật Khẩu");
        btn_doimatkhau.setBorderPainted(false);
        btn_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimatkhauActionPerformed(evt);
            }
        });

        lbl_title_sdt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_sdt.setText("SDT:");

        lbl_tennguoidung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tennguoidung.setText("Nguyễn Trọng Nghĩa");
        lbl_tennguoidung.setToolTipText("");

        lbl_taikhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_taikhoan.setText("n********");
        lbl_taikhoan.setToolTipText("");

        lbl_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_matkhau.setText("************");
        lbl_matkhau.setToolTipText("");

        lbl_diachi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_diachi.setText("NV2605");
        lbl_diachi.setToolTipText("");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_email.setText("ng**************05@gmail.com");
        lbl_email.setToolTipText("");

        lbl_sdt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_sdt.setText("09*******31");
        lbl_sdt.setToolTipText("");

        btn_dangxuat.setBackground(new java.awt.Color(50, 50, 50));
        btn_dangxuat.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangxuat.setText("Đăng Xuất");
        btn_dangxuat.setBorderPainted(false);
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_title_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_title_tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_doimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title_email, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_title_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_title_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_title_tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_title_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_title_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_doimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_matkhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                        .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_title_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_title_email, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_title_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1250, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimatkhauActionPerformed
        // TODO add your handling code here:'
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        FormDMK dmk = new FormDMK(parent, true);
        dmk.setTitle("Đổi Mật Khẩu");
        dmk.setVisible(true);
    }//GEN-LAST:event_btn_doimatkhauActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        // TODO add your handling code here:
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        // Đóng Frame cha
        if (window != null) {
        window.dispose();
        }

        // Mở lại form đăng nhập
        FormDN formdn = new FormDN();
        formdn.setVisible(true);
    }//GEN-LAST:event_btn_dangxuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhatanh;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_doimatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_avatar;
    private javax.swing.JLabel lbl_diachi;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_header_tennguoidung;
    private javax.swing.JLabel lbl_matkhau;
    private javax.swing.JLabel lbl_sdt;
    private javax.swing.JLabel lbl_taikhoan;
    private javax.swing.JLabel lbl_tennguoidung;
    private javax.swing.JLabel lbl_title_diachi;
    private javax.swing.JLabel lbl_title_email;
    private javax.swing.JLabel lbl_title_matkhau;
    private javax.swing.JLabel lbl_title_sdt;
    private javax.swing.JLabel lbl_title_taikhoan;
    private javax.swing.JLabel lbl_title_tennguoidung;
    // End of variables declaration//GEN-END:variables
}
