/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import App.HintSupport;
import BLL.HangHoaBLL;
import BLL.NhaCungCapBLL;
import DTO.HangHoaDTO;
import DTO.NhaCungCapDTO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nghia
 */
public class ChildformQLHH extends javax.swing.JPanel {
    
    public static ChildformQLHH instance;
    
    private HangHoaBLL bll = new HangHoaBLL();
    private NhaCungCapBLL nccBLL = new NhaCungCapBLL(); // Để lấy danh sách NCC

    /**
     * Creates new form ChildformQLHH
     */
    public ChildformQLHH() {
        instance = this;
        
        initComponents();
        
        HintSupport.addHint(tf_giaban,"Nhập giá bán sản phẩm...");
        HintSupport.addHint(tf_mahh,"Nhập mã sản phẩm...");
        HintSupport.addHint(tf_soluong,"Nhập số lượng...");
        HintSupport.addHint(tf_tenhanghoa,"Nhập tên sản phẩm...");
        HintSupport.addHint(tf_timkiem,"Tìm Kiếm");
        HintSupport.addHint(tf_gianhap,"Nhập giá nhập sản phẩm...");
        
        cauHinhBang();
        loadComboboxNCC();
        loadTable();
        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                loadComboboxNCC();
            }
        });
    }
    
    public void loadComboboxNCC() {
        cb_congty.removeAllItems();
        ArrayList<NhaCungCapDTO> listNCC = nccBLL.layDanhSach();
        
        for (NhaCungCapDTO ncc : listNCC) {
            cb_congty.addItem(ncc.getMaNCC() + " - " + ncc.getTenCongTy());
        }
    }
    
    private void cauHinhBang() {
        String[] columnNames = {
            // Sửa tiêu đề cột cho rõ nghĩa
            "Mã HH", "Tên Hàng Hóa", "SL Nhập", "SL Còn", "Tổng Vốn",  "Giá Nhập", "Giá Bán", "Mã NCC"
        };
        
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tb_dulieu.setModel(model);
    }

    public void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tb_dulieu.getModel();
        model.setRowCount(0); 
        
        ArrayList<HangHoaDTO> list = bll.layDanhSach(); 
        
        DecimalFormat df = new DecimalFormat("#,###");
        
        for (HangHoaDTO hh : list) {
            model.addRow(new Object[]{
                hh.getMaHangHoa(),
                hh.getTenHangHoa(),
                hh.getSoLuongNhap(),      // Cột 2
                hh.getSoLuongConLai(),    // Cột 3
                df.format(hh.getGiaNhap()),           
                df.format(hh.getTongTienNhap()), // Cột 5: Tổng Tiền
                df.format(hh.getGiaBan()),
                hh.getMaNhaCungCap()
            });
        }
    }
    
    private void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tb_dulieu.getModel();
        model.setRowCount(0);
        
        String tuKhoa = tf_timkiem.getText();
        ArrayList<HangHoaDTO> list = bll.timKiemHH(tuKhoa);
        
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###"); // Format tiền cho đẹp (tùy chọn)

        for (HangHoaDTO hh : list) {
            model.addRow(new Object[]{
                hh.getMaHangHoa(), 
                hh.getTenHangHoa(), 
                hh.getSoLuongConLai(), // <--- SỬA: Dùng getSoLuongConLai() thay vì getSoLuong()
                df.format(hh.getGiaBan()), // Format tiền
                df.format(hh.getGiaNhap()), 
                hh.getMaNhaCungCap()
            });
        }
    }

    private void lamMoiForm() {
        tf_mahh.setText("");
        tf_tenhanghoa.setText("");
        tf_soluong.setText("");
        tf_giaban.setText("");
        tf_gianhap.setText("");
        if(cb_congty.getItemCount() > 0) cb_congty.setSelectedIndex(0);
        tf_mahh.requestFocus();
    }
    
    private java.awt.Component getFrame() {
        return javax.swing.SwingUtilities.getWindowAncestor(this);
    }
    
    private boolean checkInput(javax.swing.JTextField tf, String hint, String name) {
        if (tf.getText().trim().isEmpty() || tf.getText().equals(hint)) {
            JOptionPane.showMessageDialog(getFrame(), "Vui lòng nhập " + name + "!");
            tf.requestFocus();
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tenhanghoa = new javax.swing.JLabel();
        tf_tenhanghoa = new javax.swing.JTextField();
        lbl_soluong = new javax.swing.JLabel();
        tf_soluong = new javax.swing.JTextField();
        lbl_giaban = new javax.swing.JLabel();
        tf_giaban = new javax.swing.JTextField();
        lbl_congty = new javax.swing.JLabel();
        cb_congty = new javax.swing.JComboBox<>();
        tf_mahh = new javax.swing.JTextField();
        lbl_mahh = new javax.swing.JLabel();
        tf_timkiem = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        lbl_gianhap = new javax.swing.JLabel();
        tf_gianhap = new javax.swing.JTextField();
        lbl_timkiem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dulieu = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 238, 240));

        lbl_tenhanghoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tenhanghoa.setText("Tên Hàng Hóa:");
        lbl_tenhanghoa.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_tenhanghoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_tenhanghoa.setText("jTextField1");
        tf_tenhanghoa.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_soluong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_soluong.setText("Số Lượng:");
        lbl_soluong.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_soluong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_soluong.setText("jTextField1");
        tf_soluong.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_giaban.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_giaban.setText("Giá Bán:");
        lbl_giaban.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_giaban.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_giaban.setText("jTextField1");
        tf_giaban.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_congty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_congty.setText("Công Ty:");
        lbl_congty.setPreferredSize(new java.awt.Dimension(85, 16));

        cb_congty.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cb_congty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tf_mahh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_mahh.setText("jTextField1");
        tf_mahh.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_mahh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_mahh.setText("Mã Hàng Hóa:");
        lbl_mahh.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_timkiem.setText("jTextField1");
        tf_timkiem.setPreferredSize(new java.awt.Dimension(86, 16));
        tf_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_timkiemKeyReleased(evt);
            }
        });

        btn_them.setBackground(new java.awt.Color(50, 50, 50));
        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.setBorderPainted(false);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        lbl_gianhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_gianhap.setText("Giá Nhập:");
        lbl_gianhap.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_gianhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_gianhap.setText("jTextField1");
        tf_gianhap.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_timkiem.setText("Tìm Kiếm:");
        lbl_timkiem.setPreferredSize(new java.awt.Dimension(85, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mahh, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_mahh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_tenhanghoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_congty, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_congty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_gianhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(lbl_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_mahh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mahh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_congty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_congty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 310));

        tb_dulieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_dulieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dulieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dulieu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1250, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (checkInput(tf_mahh, "Nhập mã sản phẩm...", "Mã Hàng Hóa")) return;
        if (checkInput(tf_tenhanghoa, "Nhập tên sản phẩm...", "Tên Hàng Hóa")) return;
        if (checkInput(tf_soluong, "Nhập số lượng...", "Số Lượng")) return;
        if (checkInput(tf_giaban, "Nhập giá bán sản phẩm...", "Giá Bán")) return;
        if (checkInput(tf_gianhap, "Nhập giá nhập sản phẩm...", "Giá Nhập")) return;

        // 2. Tạo DTO và Xử lý dữ liệu số
        HangHoaDTO hh = new HangHoaDTO();
        hh.setMaHangHoa(tf_mahh.getText().trim());
        hh.setTenHangHoa(tf_tenhanghoa.getText().trim());
        
        try {
            // Chuyển đổi chuỗi sang số
            int sl = Integer.parseInt(tf_soluong.getText().trim());
            double giaBan = Double.parseDouble(tf_giaban.getText().trim());
            double giaNhap = Double.parseDouble(tf_gianhap.getText().trim());
            
            // Kiểm tra số âm
            if (sl < 0 || giaBan < 0 || giaNhap < 0) {
                JOptionPane.showMessageDialog(getFrame(), "Số lượng và Giá phải lớn hơn hoặc bằng 0!");
                return;
            }
            
            hh.setSoLuongNhap(sl); // Sửa: Set vào Số Lượng Nhập
            hh.setGiaBan(giaBan);
            hh.setGiaNhap(giaNhap);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(getFrame(), "Lỗi: Số lượng và Giá phải là số hợp lệ!");
            return;
        }

        // 3. Lấy Mã NCC từ ComboBox (Cắt chuỗi "Mã - Tên")
        if (cb_congty.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(getFrame(), "Vui lòng chọn Công Ty!");
            return;
        }
        String selectedNCC = cb_congty.getSelectedItem().toString();
        // Lấy phần trước dấu " - "
        String maNCC = selectedNCC.split(" - ")[0]; 
        hh.setMaNhaCungCap(maNCC);

        // 4. Gọi BLL thêm
        String ketQua = bll.themHangHoa(hh);
        JOptionPane.showMessageDialog(getFrame(), ketQua);

        // 5. Thành công thì load lại
        if (ketQua.contains("thành công")) {
            loadTable();
            lamMoiForm();
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void tf_timkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_timkiemKeyReleased
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_tf_timkiemKeyReleased

    private void tb_dulieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dulieuMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = tb_dulieu.getSelectedRow();
            if (row >= 0) {
                try {
                    String ma = tb_dulieu.getValueAt(row, 0).toString();
                    String ten = tb_dulieu.getValueAt(row, 1).toString();
                    int slNhap = Integer.parseInt(tb_dulieu.getValueAt(row, 2).toString()); 
                    String giaNhapStr = tb_dulieu.getValueAt(row, 4).toString().replace(",", "");
                    String giaBanStr = tb_dulieu.getValueAt(row, 6).toString().replace(",", "");
                    double giaNhap = Double.parseDouble(giaNhapStr);
                    double giaBan = Double.parseDouble(giaBanStr);
                    String maNCC = tb_dulieu.getValueAt(row, 7).toString();
                    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    FormSuaHH sua = new FormSuaHH(parent, true);
                    
                    sua.setDuLieu(ma, ten, slNhap, giaNhap, giaBan, maNCC);
                    
                    sua.setTitle("Điều chỉnh thông tin nhập hàng");
                    sua.setVisible(true);
                    loadTable();
                    
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(getFrame(), "Lỗi khi lấy dữ liệu: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_tb_dulieuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cb_congty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_congty;
    private javax.swing.JLabel lbl_giaban;
    private javax.swing.JLabel lbl_gianhap;
    private javax.swing.JLabel lbl_mahh;
    private javax.swing.JLabel lbl_soluong;
    private javax.swing.JLabel lbl_tenhanghoa;
    private javax.swing.JLabel lbl_timkiem;
    private javax.swing.JTable tb_dulieu;
    private javax.swing.JTextField tf_giaban;
    private javax.swing.JTextField tf_gianhap;
    private javax.swing.JTextField tf_mahh;
    private javax.swing.JTextField tf_soluong;
    private javax.swing.JTextField tf_tenhanghoa;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
}
