/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import App.HintSupport;

/**
 *
 * @author Nghia
 */
public class ChildformQLNCC extends javax.swing.JPanel {

    /**
     * Creates new form ChildformQLNCC
     */
    public ChildformQLNCC() {
        initComponents();
        
        // TextHint
        HintSupport.addHint(tf_diachincc, "Nhập địa chỉ...");
        HintSupport.addHint(tf_mancc, "Nhập mã nhà cung cấp...");
        HintSupport.addHint(tf_emailncc,"Nhập email...");
        HintSupport.addHint(tf_nguoilh, "Nhập tên người liên hệ chính...");
        HintSupport.addHint(tf_sdtncc, "Nhập SDT...");
        HintSupport.addHint(tf_timkiem, "Tìm Kiếm");
        HintSupport.addHint(tf_tencongtyncc, "Nhập tên công ty...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_thongtin = new javax.swing.JPanel();
        lbl_diachincc = new javax.swing.JLabel();
        lbl_sdtncc = new javax.swing.JLabel();
        lbl_nguoilh = new javax.swing.JLabel();
        lbl_emailncc = new javax.swing.JLabel();
        tf_diachincc = new javax.swing.JTextField();
        tf_sdtncc = new javax.swing.JTextField();
        tf_emailncc = new javax.swing.JTextField();
        tf_nguoilh = new javax.swing.JTextField();
        lbl_mancc = new javax.swing.JLabel();
        tf_mancc = new javax.swing.JTextField();
        tf_timkiem = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_capnhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        tf_tencongtyncc = new javax.swing.JTextField();
        lbl_tencongtyncc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dulieu = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_thongtin.setBackground(new java.awt.Color(235, 238, 240));

        lbl_diachincc.setText("Địa Chỉ:");
        lbl_diachincc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_sdtncc.setText("SDT Liên Hệ:");
        lbl_sdtncc.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_nguoilh.setText("Người Liện Hệ Chính:");
        lbl_nguoilh.setPreferredSize(new java.awt.Dimension(85, 16));

        lbl_emailncc.setText("Email:");
        lbl_emailncc.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_diachincc.setText("jTextField1");
        tf_diachincc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_sdtncc.setText("jTextField1");
        tf_sdtncc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_emailncc.setText("jTextField1");
        tf_emailncc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_nguoilh.setText("jTextField1");
        tf_nguoilh.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_mancc.setText("Mã Nhà Cung Cấp:");
        lbl_mancc.setPreferredSize(new java.awt.Dimension(85, 16));

        tf_mancc.setText("jTextField1");
        tf_mancc.setPreferredSize(new java.awt.Dimension(86, 16));

        tf_timkiem.setText("jTextField1");
        tf_timkiem.setPreferredSize(new java.awt.Dimension(86, 16));

        btn_them.setBackground(new java.awt.Color(50, 50, 50));
        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.setBorderPainted(false);

        btn_capnhat.setBackground(new java.awt.Color(50, 50, 50));
        btn_capnhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_capnhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_capnhat.setText("Cập Nhật");
        btn_capnhat.setBorderPainted(false);
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(50, 50, 50));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.setBorderPainted(false);

        btn_timkiem.setBackground(new java.awt.Color(50, 50, 50));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setText("Search");
        btn_timkiem.setBorderPainted(false);

        tf_tencongtyncc.setText("jTextField1");
        tf_tencongtyncc.setPreferredSize(new java.awt.Dimension(86, 16));

        lbl_tencongtyncc.setText("Tên Công Ty:");
        lbl_tencongtyncc.setPreferredSize(new java.awt.Dimension(85, 16));

        javax.swing.GroupLayout Pnl_thongtinLayout = new javax.swing.GroupLayout(Pnl_thongtin);
        Pnl_thongtin.setLayout(Pnl_thongtinLayout);
        Pnl_thongtinLayout.setHorizontalGroup(
            Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_emailncc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_nguoilh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_sdtncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_sdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_emailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                        .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        Pnl_thongtinLayout.setVerticalGroup(
            Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_thongtinLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(126, 126, 126)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_thongtinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tencongtyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_emailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_emailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nguoilh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        add(Pnl_thongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 310));

        tb_dulieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_dulieu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1250, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // Tạo dialog modal
        FormSuaNCC suancc = new FormSuaNCC(parent, true);
        suancc.setTitle("Cập Nhật Nhà Cung Cấp");
        suancc.setVisible(true);
    }//GEN-LAST:event_btn_capnhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_thongtin;
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_diachincc;
    private javax.swing.JLabel lbl_emailncc;
    private javax.swing.JLabel lbl_mancc;
    private javax.swing.JLabel lbl_nguoilh;
    private javax.swing.JLabel lbl_sdtncc;
    private javax.swing.JLabel lbl_tencongtyncc;
    private javax.swing.JTable tb_dulieu;
    private javax.swing.JTextField tf_diachincc;
    private javax.swing.JTextField tf_emailncc;
    private javax.swing.JTextField tf_mancc;
    private javax.swing.JTextField tf_nguoilh;
    private javax.swing.JTextField tf_sdtncc;
    private javax.swing.JTextField tf_tencongtyncc;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
}
