/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import App.LuuTruTK;
import BLL.TaiKhoanBLL;
import javax.swing.JOptionPane;

/**
 *
 * @author Nghia
 */
public class FormDMK extends javax.swing.JDialog {
    
    private TaiKhoanBLL taiKhoanBLL = new TaiKhoanBLL(); // Gọi BLL
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDMK.class.getName());

    /**
     * Creates new form FormDMK
     */
    
    private boolean isPasswordVisible = false;
    
    public FormDMK(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_mkcu = new javax.swing.JLabel();
        lbl_mkmoi = new javax.swing.JLabel();
        lbl_nhaplaimk = new javax.swing.JLabel();
        lbl_hienmk = new javax.swing.JLabel();
        lbl_icon_hienmatkhau = new javax.swing.JLabel();
        psf_mkcu = new javax.swing.JPasswordField();
        psf_mkmoi = new javax.swing.JPasswordField();
        psf_nhaplaimk = new javax.swing.JPasswordField();
        btn_xacnhan = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(235, 238, 240));
        setResizable(false);

        lbl_mkcu.setText("Mật Khẩu Cũ:");
        lbl_mkcu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_mkmoi.setText("Mật Khẩu Mới:");
        lbl_mkmoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_nhaplaimk.setText("Nhập Lại Mật Khẩu Mới:");
        lbl_nhaplaimk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_hienmk.setText("Hiện mật khẩu");
        lbl_hienmk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_icon_hienmatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeclose.png"))); // NOI18N
        lbl_icon_hienmatkhau.setToolTipText("");
        lbl_icon_hienmatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_icon_hienmatkhauMouseClicked(evt);
            }
        });

        btn_xacnhan.setText("Xác Nhận");
        btn_xacnhan.setBackground(new java.awt.Color(50, 50, 50));
        btn_xacnhan.setBorderPainted(false);
        btn_xacnhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.setBackground(new java.awt.Color(50, 50, 50));
        btn_huy.setBorderPainted(false);
        btn_huy.setForeground(new java.awt.Color(255, 255, 255));
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_xacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_hienmk)
                                .addGap(4, 4, 4)
                                .addComponent(lbl_icon_hienmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_mkcu)
                                    .addComponent(lbl_mkmoi)
                                    .addComponent(lbl_nhaplaimk))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(psf_mkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psf_mkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psf_nhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psf_mkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psf_mkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psf_nhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_icon_hienmatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_hienmk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanActionPerformed
        // TODO add your handling code here:
        // 0. Kiểm tra an toàn: Xem có ai đang đăng nhập không?
        if (LuuTruTK.taiKhoanHienTai == null) {
            JOptionPane.showMessageDialog(this, "Lỗi: Chưa đăng nhập!");
            return;
        }

        // 1. Lấy Tên Đăng Nhập từ biến toàn cục (Session)
        String tenDangNhap = LuuTruTK.taiKhoanHienTai.getTenDangNhap();

        // 2. Lấy dữ liệu từ các ô nhập
        String mkCu = new String(psf_mkcu.getPassword());
        String mkMoi = new String(psf_mkmoi.getPassword());
        String mkNhapLai = new String(psf_nhaplaimk.getPassword());

        // 3. Gọi BLL xử lý (Hàm này code ở phần trước)
        String ketQua = taiKhoanBLL.doiMatKhau(tenDangNhap, mkCu, mkMoi, mkNhapLai);

        // 4. Hiển thị kết quả
        if (ketQua.equals("Đổi mật khẩu thành công")) {
            JOptionPane.showMessageDialog(this, ketQua);
            
            // (Tùy chọn) Cập nhật lại mật khẩu trong Session luôn để đồng bộ
            LuuTruTK.taiKhoanHienTai.setMatKhau(mkMoi);
           
            if (ChildformQLNV.instance != null) {
                ChildformQLNV.instance.loadTable(); // <--- Gọi hàm loadTable() từ xa
            }
            
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, ketQua);
        }
    }//GEN-LAST:event_btn_xacnhanActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_huyActionPerformed

    private void lbl_icon_hienmatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_icon_hienmatkhauMouseClicked
        // TODO add your handling code here:
        if(isPasswordVisible){
            psf_mkcu.setEchoChar('*');
            psf_mkmoi.setEchoChar('*');
            psf_nhaplaimk.setEchoChar('*');
            lbl_icon_hienmatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeclose.png")));
            isPasswordVisible = false;
        }
        else{
            psf_mkcu.setEchoChar((char)0);
            psf_mkmoi.setEchoChar((char)0);
            psf_nhaplaimk.setEchoChar((char)0);
            lbl_icon_hienmatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeopen.png")));
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_lbl_icon_hienmatkhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormDMK dialog = new FormDMK(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_xacnhan;
    private javax.swing.JLabel lbl_hienmk;
    private javax.swing.JLabel lbl_icon_hienmatkhau;
    private javax.swing.JLabel lbl_mkcu;
    private javax.swing.JLabel lbl_mkmoi;
    private javax.swing.JLabel lbl_nhaplaimk;
    private javax.swing.JPasswordField psf_mkcu;
    private javax.swing.JPasswordField psf_mkmoi;
    private javax.swing.JPasswordField psf_nhaplaimk;
    // End of variables declaration//GEN-END:variables
}
