/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BLL.NhanVienBLL;
import DTO.NhanVienDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Nghia
 */
public class FormSuaTTNhanVien extends javax.swing.JDialog {
    
    private NhanVienBLL bll = new NhanVienBLL();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSuaTTNhanVien.class.getName());

    /**
     * Creates new form FormSuaTTNguoiDung
     */
    public FormSuaTTNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(parent);
    }
    
    public void setDuLieu(NhanVienDTO nv) {
        lbl_manv.setText(nv.getMaNV()); // QUAN TRỌNG: Mã NV là khóa, không cho sửa
        tf_nhanvien.setText(nv.getTenNV());
        tf_diachi.setText(nv.getDiaChi());
        tf_email.setText(nv.getEmail());
        tf_sdt.setText(nv.getSdt());
        
        tf_taikhoan.setText(nv.getTenDangNhap());
        tf_matkhau.setText(nv.getMatKhau());
        cb_vaitro.setSelectedItem(nv.getVaiTro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nhanvien = new javax.swing.JLabel();
        lbl_diachi = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_sdt = new javax.swing.JLabel();
        tf_nhanvien = new javax.swing.JTextField();
        tf_diachi = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_sdt = new javax.swing.JTextField();
        lbl_matkhau = new javax.swing.JLabel();
        tf_matkhau = new javax.swing.JTextField();
        lbl_taikhoan = new javax.swing.JLabel();
        tf_taikhoan = new javax.swing.JTextField();
        lbl_vaitro = new javax.swing.JLabel();
        cb_vaitro = new javax.swing.JComboBox<>();
        lbl_title_manv = new javax.swing.JLabel();
        lbl_manv = new javax.swing.JLabel();
        btn_capnhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(235, 238, 240));

        lbl_nhanvien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nhanvien.setText("Tên Nhân Viên:");

        lbl_diachi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_diachi.setText("Địa Chỉ:");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_email.setText("Email:");

        lbl_sdt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_sdt.setText("Số Điện Thoại:");

        tf_nhanvien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_nhanvien.setText("Nguyễn Trọng Nghĩa");

        tf_diachi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_diachi.setText("Vĩnh Yên - Phú Thọ");

        tf_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_email.setText("nghianguyen262005@gmail.com");

        tf_sdt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_sdt.setText("0976338231");

        lbl_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_matkhau.setText("Mật Khẩu:");

        tf_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_matkhau.setText("nghia123224");

        lbl_taikhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_taikhoan.setText("Tài Khoản:");

        tf_taikhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tf_taikhoan.setText("nghia123224");

        lbl_vaitro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_vaitro.setText("Vai Trò:");

        cb_vaitro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cb_vaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "NhanVien" }));

        lbl_title_manv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_manv.setText("Mã NV:");

        lbl_manv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_manv.setText("NV033");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_title_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_vaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_vaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_matkhau))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_sdt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_email))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_diachi))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_nhanvien)
                            .addGap(5, 5, 5)
                            .addComponent(tf_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_title_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_vaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_vaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        btn_capnhat.setBackground(new java.awt.Color(50, 50, 50));
        btn_capnhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_capnhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_capnhat.setText("Xác Nhận");
        btn_capnhat.setBorderPainted(false);
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(50, 50, 50));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.setBorderPainted(false);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_huy.setBackground(new java.awt.Color(50, 50, 50));
        btn_huy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_huy.setForeground(new java.awt.Color(255, 255, 255));
        btn_huy.setText("Hủy");
        btn_huy.setBorderPainted(false);
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
        NhanVienDTO nv = new NhanVienDTO();
        
        // Lấy dữ liệu mới
        nv.setMaNV(lbl_manv.getText()); // Lấy từ label (không sửa được)
        nv.setTenNV(tf_nhanvien.getText());
        nv.setDiaChi(tf_diachi.getText());
        nv.setEmail(tf_email.getText());
        nv.setSdt(tf_sdt.getText());
        
        nv.setTenDangNhap(tf_taikhoan.getText());
        nv.setMatKhau(tf_matkhau.getText());
        nv.setVaiTro(cb_vaitro.getSelectedItem().toString());
        
        // Gọi BLL cập nhật
        String ketQua = bll.capNhatNhanVien(nv);
        JOptionPane.showMessageDialog(this, ketQua);
        
        if (ketQua.contains("thành công")) {
            this.dispose(); // Đóng form để quay về danh sách
        }
    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa nhân viên " + lbl_manv.getText() + " không?\n" +
                "Hành động này sẽ xóa cả tài khoản liên quan!", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String maNV = lbl_manv.getText();
            
            // 3. Gọi BLL xóa
            String kq = bll.xoaNhanVien(maNV);
            JOptionPane.showMessageDialog(this, kq);
            
            // 4. Nếu thành công -> Đóng form
            if (kq.contains("thành công")) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormSuaTTNhanVien dialog = new FormSuaTTNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_vaitro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_diachi;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_manv;
    private javax.swing.JLabel lbl_matkhau;
    private javax.swing.JLabel lbl_nhanvien;
    private javax.swing.JLabel lbl_sdt;
    private javax.swing.JLabel lbl_taikhoan;
    private javax.swing.JLabel lbl_title_manv;
    private javax.swing.JLabel lbl_vaitro;
    private javax.swing.JTextField tf_diachi;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_matkhau;
    private javax.swing.JTextField tf_nhanvien;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_taikhoan;
    // End of variables declaration//GEN-END:variables
}
