/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Nghia
 */
public class UImain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UImain.class.getName());
    
    Color Maubinhthuong = new Color(50, 50, 50);
    Color HieuUngMau = new Color(65, 65, 65);
    Color ChonMau = new Color(65, 65, 65);
    JButton chonButton = null;
    /**
     * Creates new form UImain
     */
    public UImain() {
        initComponents();
        initChildForm();
        
        //set title của Jframe
        setTitle("Quản Lý Bán Balo-Cặp Sách");
        
        //set hiệu ứng cho button
        setHieuUngBTN(btn_thongke);
        setHieuUngBTN(btn_quanlydonhang);
        setHieuUngBTN(btn_quanlyncc);
        setHieuUngBTN(btn_quanlydvvc);
        setHieuUngBTN(btn_quanlyhanghoa);
        setHieuUngBTN(btn_quanlyvoucher);
        setHieuUngBTN(btn_taikhoan);
        setHieuUngBTN(btn_quanlynhanvien);
    }
    private void initChildForm(){
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        
        ChildformThongke thongke = new ChildformThongke();
        ChildformQLDH donhang = new ChildformQLDH();
        ChildformQLNCC nhacungcap = new ChildformQLNCC();
        ChildformQLDVVC donvivanchuyen = new ChildformQLDVVC();
        ChildformQLHH hanghoa = new ChildformQLHH();
        ChildformQLVoucher voucher = new ChildformQLVoucher();
        ChildformTaiKhoan taikhoan = new ChildformTaiKhoan();
        ChildformQLNV nhanvien = new ChildformQLNV();
        
        Pnl_childform.add(thongke, "thongke");
        Pnl_childform.add(donhang, "donhang");
        Pnl_childform.add(nhacungcap, "nhacungcap");
        Pnl_childform.add(donvivanchuyen, "donvivanchuyen");
        Pnl_childform.add(hanghoa, "hanghoa");
        Pnl_childform.add(voucher, "voucher");
        Pnl_childform.add(taikhoan, "taikhoan");
        Pnl_childform.add(nhanvien, "nhanvien");
    }
    public void setHieuUngBTN(JButton button){
        
        button.setBackground(Maubinhthuong);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(true);
        
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void ChuotVao(java.awt.event.MouseEvent evt){
                if(button != chonButton){
                    button.setBackground(HieuUngMau);
                }
            }
            public void ChuotRa(java.awt.event.MouseEvent evt){
                if(button != chonButton){
                    button.setBackground(Maubinhthuong);
                }
            }
        });
        button.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if(chonButton != null){
                    chonButton.setBackground(Maubinhthuong);
                }
                chonButton = button;
                button.setBackground(ChonMau);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_tong = new javax.swing.JPanel();
        Pnl_sidebar = new javax.swing.JPanel();
        Pnl_header = new javax.swing.JPanel();
        lbl_anhheader = new javax.swing.JLabel();
        lbl_header1 = new javax.swing.JLabel();
        lbl_header2 = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JButton();
        btn_quanlydonhang = new javax.swing.JButton();
        btn_quanlyncc = new javax.swing.JButton();
        btn_quanlydvvc = new javax.swing.JButton();
        btn_quanlyhanghoa = new javax.swing.JButton();
        btn_quanlyvoucher = new javax.swing.JButton();
        btn_taikhoan = new javax.swing.JButton();
        btn_quanlynhanvien = new javax.swing.JButton();
        Pnl_childform = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Pnl_tong.setPreferredSize(new java.awt.Dimension(1600, 900));
        Pnl_tong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_sidebar.setBackground(new java.awt.Color(50, 50, 50));
        Pnl_sidebar.setPreferredSize(new java.awt.Dimension(350, 900));

        Pnl_header.setBackground(new java.awt.Color(80, 80, 80));
        Pnl_header.setPreferredSize(new java.awt.Dimension(350, 200));
        Pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_anhheader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/balo (1).png"))); // NOI18N
        Pnl_header.add(lbl_anhheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lbl_header1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        lbl_header1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_header1.setText("Quản Lý ");
        lbl_header1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_header1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Pnl_header.add(lbl_header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 40));

        lbl_header2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_header2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lbl_header2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_header2.setText("Bán Balo-Cặp Sách");
        Pnl_header.add(lbl_header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        btn_thongke.setBackground(new java.awt.Color(50, 50, 50));
        btn_thongke.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_thongke.setForeground(new java.awt.Color(255, 255, 255));
        btn_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        btn_thongke.setText("Thống Kê");
        btn_thongke.setBorderPainted(false);
        btn_thongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_thongke.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_thongke.setIconTextGap(10);
        btn_thongke.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });

        btn_quanlydonhang.setBackground(new java.awt.Color(50, 50, 50));
        btn_quanlydonhang.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_quanlydonhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_quanlydonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/order.png"))); // NOI18N
        btn_quanlydonhang.setText("Quản Lý Đơn Hàng");
        btn_quanlydonhang.setBorderPainted(false);
        btn_quanlydonhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_quanlydonhang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_quanlydonhang.setIconTextGap(10);
        btn_quanlydonhang.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_quanlydonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlydonhangActionPerformed(evt);
            }
        });

        btn_quanlyncc.setBackground(new java.awt.Color(50, 50, 50));
        btn_quanlyncc.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_quanlyncc.setForeground(new java.awt.Color(255, 255, 255));
        btn_quanlyncc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/store.png"))); // NOI18N
        btn_quanlyncc.setText("Quản Lý Nhà Cung Cấp");
        btn_quanlyncc.setBorderPainted(false);
        btn_quanlyncc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_quanlyncc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_quanlyncc.setIconTextGap(10);
        btn_quanlyncc.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_quanlyncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlynccActionPerformed(evt);
            }
        });

        btn_quanlydvvc.setBackground(new java.awt.Color(50, 50, 50));
        btn_quanlydvvc.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_quanlydvvc.setForeground(new java.awt.Color(255, 255, 255));
        btn_quanlydvvc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delivery.png"))); // NOI18N
        btn_quanlydvvc.setText("Quản Lý Đơn Vị Vận Chuyển");
        btn_quanlydvvc.setBorderPainted(false);
        btn_quanlydvvc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_quanlydvvc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_quanlydvvc.setIconTextGap(10);
        btn_quanlydvvc.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_quanlydvvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlydvvcActionPerformed(evt);
            }
        });

        btn_quanlyhanghoa.setBackground(new java.awt.Color(50, 50, 50));
        btn_quanlyhanghoa.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_quanlyhanghoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_quanlyhanghoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/donhang.png"))); // NOI18N
        btn_quanlyhanghoa.setText("Quản Lý Hàng Hóa");
        btn_quanlyhanghoa.setBorderPainted(false);
        btn_quanlyhanghoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_quanlyhanghoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_quanlyhanghoa.setIconTextGap(10);
        btn_quanlyhanghoa.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_quanlyhanghoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlyhanghoaActionPerformed(evt);
            }
        });

        btn_quanlyvoucher.setBackground(new java.awt.Color(50, 50, 50));
        btn_quanlyvoucher.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_quanlyvoucher.setForeground(new java.awt.Color(255, 255, 255));
        btn_quanlyvoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ticket.png"))); // NOI18N
        btn_quanlyvoucher.setText("Quản Lý Voucher");
        btn_quanlyvoucher.setBorderPainted(false);
        btn_quanlyvoucher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_quanlyvoucher.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_quanlyvoucher.setIconTextGap(10);
        btn_quanlyvoucher.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_quanlyvoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlyvoucherActionPerformed(evt);
            }
        });

        btn_taikhoan.setBackground(new java.awt.Color(50, 50, 50));
        btn_taikhoan.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_taikhoan.setForeground(new java.awt.Color(255, 255, 255));
        btn_taikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/taikhoan.png"))); // NOI18N
        btn_taikhoan.setText("Tài Khoản");
        btn_taikhoan.setBorderPainted(false);
        btn_taikhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_taikhoan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_taikhoan.setIconTextGap(10);
        btn_taikhoan.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taikhoanActionPerformed(evt);
            }
        });

        btn_quanlynhanvien.setBackground(new java.awt.Color(50, 50, 50));
        btn_quanlynhanvien.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btn_quanlynhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btn_quanlynhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nhanvien.png"))); // NOI18N
        btn_quanlynhanvien.setText("Quản Lý Nhân Viên");
        btn_quanlynhanvien.setBorderPainted(false);
        btn_quanlynhanvien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_quanlynhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_quanlynhanvien.setIconTextGap(10);
        btn_quanlynhanvien.setMargin(new java.awt.Insets(2, 30, 3, 14));
        btn_quanlynhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlynhanvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_sidebarLayout = new javax.swing.GroupLayout(Pnl_sidebar);
        Pnl_sidebar.setLayout(Pnl_sidebarLayout);
        Pnl_sidebarLayout.setHorizontalGroup(
            Pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Pnl_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlydonhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlyncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlydvvc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlyhanghoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlyvoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pnl_sidebarLayout.setVerticalGroup(
            Pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_sidebarLayout.createSequentialGroup()
                .addComponent(Pnl_header, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlydonhang, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlyncc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlydvvc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlyhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlyvoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Pnl_tong.add(Pnl_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Pnl_childform.setBackground(new java.awt.Color(242, 241, 255));
        Pnl_childform.setPreferredSize(new java.awt.Dimension(1250, 900));
        Pnl_childform.setLayout(new java.awt.CardLayout());
        Pnl_tong.add(Pnl_childform, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_tong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_tong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_quanlydonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlydonhangActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "donhang");
    }//GEN-LAST:event_btn_quanlydonhangActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "thongke");
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void btn_quanlynccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlynccActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "nhacungcap");
    }//GEN-LAST:event_btn_quanlynccActionPerformed

    private void btn_quanlydvvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlydvvcActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "donvivanchuyen");
    }//GEN-LAST:event_btn_quanlydvvcActionPerformed

    private void btn_quanlyhanghoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlyhanghoaActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "hanghoa");
    }//GEN-LAST:event_btn_quanlyhanghoaActionPerformed

    private void btn_quanlyvoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlyvoucherActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "voucher");
    }//GEN-LAST:event_btn_quanlyvoucherActionPerformed

    private void btn_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taikhoanActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform, "taikhoan");
    }//GEN-LAST:event_btn_taikhoanActionPerformed

    private void btn_quanlynhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlynhanvienActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Pnl_childform.getLayout();
        card.show(Pnl_childform,"nhanvien");
    }//GEN-LAST:event_btn_quanlynhanvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UImain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_childform;
    private javax.swing.JPanel Pnl_header;
    private javax.swing.JPanel Pnl_sidebar;
    private javax.swing.JPanel Pnl_tong;
    private javax.swing.JButton btn_quanlydonhang;
    private javax.swing.JButton btn_quanlydvvc;
    private javax.swing.JButton btn_quanlyhanghoa;
    private javax.swing.JButton btn_quanlyncc;
    private javax.swing.JButton btn_quanlynhanvien;
    private javax.swing.JButton btn_quanlyvoucher;
    private javax.swing.JButton btn_taikhoan;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JLabel lbl_anhheader;
    private javax.swing.JLabel lbl_header1;
    private javax.swing.JLabel lbl_header2;
    // End of variables declaration//GEN-END:variables
}
